import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ui/theme-provider";
import MobileNav from "@/components/sidebar/MobileNav";
import Profile from "@/components/sidebar/Profile";
import Sidebar from "@/components/sidebar/Sidebar";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen depro-bg font-sans antialiased",
          inter.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
            <div className="hidden bg-muted/40 md:block">
              {/* Sidebar  */}
              <Sidebar />
            </div>
            <div className="flex flex-col">
              <header className="flex justify-between items-center gap-4 border-b border-gray-700 bg-muted/40 h-[90px] px-4 lg:px-6">
                {/* mobile nav  */}
                <MobileNav />
                <Image
                  src={"/assets/images/leftmenu.png"}
                  width={48}
                  height={48}
                  className="object-cover"
                  alt="left-menu"
                />
                <h1 className="text-[32px] font-bold">Depro CMS</h1>
                {/* profile  */}
                <div className="flex items-center gap-2">
                  <h1 className="text-[20px] font-bold text-[#7547FF]">
                    RootAdmin
                  </h1>
                  <Image
                    src={"/assets/images/AdminLogo.png"}
                    width={36}
                    height={36}
                    className="object-cover"
                    alt="admin"
                  />
                </div>
              </header>
              {/* Contant  */}
              <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
                <div className="flex items-center">
                  {/* <h1 className="text-lg font-semibold md:text-2xl">
                    Depro
                  </h1> */}
                </div>
                <div className="flex flex-1" x-chunk="dashboard-02-chunk-1">
                  <div className="w-full">{children}</div>
                </div>
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
